language: python
python:
  - "2.7"
  - "3.5"
cache: pip
install:
  - python setup.py requirements -t
script:
  - pep8 -v --ignore=E501 .
  - python setup.py test -a "--cov=netbox"
after_success:
  coveralls
