language: python
python:
  - "2.7"
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  - py.test --cov=netbox
after_success:
  coveralls
