language: python
python:
  - "2.7"
  - "3.5"
cache: pip
install:
  - pip install -e .
  - pip install -e .[tests]
script:
  - pep8 -v --ignore=E501 .
  - py.test --cov=netbox
after_success:
  coveralls
